# Generated by Django 5.0.6 on 2024-08-15 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_sms_action_alter_sms_status_remove_sms_tag_sms_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='to',
        ),
        migrations.AddField(
            model_name='sms',
            name='to',
            field=models.ManyToManyField(related_name='%(class)s_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
