name: dms_dev_docker

services:
  postgres:
    image: postgres:14.0
    container_name: dms_dev_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  rabbitmq:
    image: "rabbitmq:alpine" 
    container_name: dms_dev_rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"    
      - "15672:15672"  