# Generated by Django 5.0.6 on 2024-06-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Enter the content of the comment.', verbose_name='Content'),
        ),
    ]
