# Generated by Django 5.0.6 on 2024-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=1, help_text='Enter the message of the comment.', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
