# Generated by Django 5.0.6 on 2024-10-08 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name_en', models.CharField(blank=True, max_length=35, verbose_name='First Name (English)')),
                ('middle_name_en', models.CharField(blank=True, max_length=35, verbose_name='Middle Name (English)')),
                ('last_name_en', models.CharField(blank=True, max_length=35, verbose_name='Last Name (English)')),
                ('first_name_am', models.CharField(blank=True, max_length=35, verbose_name='First Name (Amharic)')),
                ('middle_name_am', models.CharField(blank=True, max_length=35, verbose_name='Middle Name (Amharic)')),
                ('last_name_am', models.CharField(blank=True, max_length=35, verbose_name='Last Name (Amharic)')),
                ('phone_number', models.PositiveBigIntegerField(unique=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('is_first_time', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
