# Generated by Django 5.0.6 on 2024-10-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_userpermissions_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='is_first_time',
            new_name='is_verified',
        ),
    ]
