# Generated by Django 5.0.6 on 2024-10-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_userpermissions_member_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermissions',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together=set(),
        ),
    ]
