# Generated by Django 5.0.6 on 2024-08-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letterattachment',
            old_name='uploaded_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='letterattachment',
            old_name='name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='letterattachment',
            old_name='size',
            new_name='file_size',
        ),
        migrations.RemoveField(
            model_name='letterattachment',
            name='remote_file_url',
        ),
    ]
