# Generated by Django 5.0.6 on 2024-06-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this participant.', on_delete=django.db.models.deletion.CASCADE, related_name='participates_in', to='users.baseuser'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'letter')},
        ),
    ]
