# Generated by Django 5.0.6 on 2024-10-11 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('enterprises', '0001_initial'),
        ('letters', '0002_initial'),
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseparticipant',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baseparticipant',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='letters.letter'),
        ),
        migrations.AddField(
            model_name='baseparticipant',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='enterpriseparticipant',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_referenced_in_letters', to='enterprises.enterprise'),
        ),
        migrations.AddField(
            model_name='externaluserparticipant',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_referenced_in_letters', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='internaluserparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_in_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='baseparticipant',
            index=models.Index(fields=['role', 'letter'], name='participant_role_b1271a_idx'),
        ),
    ]
