# Generated by Django 5.0.6 on 2024-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='received_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
