# Generated by Django 5.0.6 on 2024-06-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_alter_letter_reference_number'),
        ('participants', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'letter')},
        ),
    ]
