# Generated by Django 5.0.6 on 2024-08-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_rename_publicenterprise_enterprise'),
        ('participants', '0003_rename_publicenterpriseparticipant_enterpriseparticipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externaluserparticipant',
            old_name='user',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='enterpriseparticipant',
            name='user',
        ),
        migrations.AddField(
            model_name='enterpriseparticipant',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_referenced_in_letters', to='enterprises.enterprise'),
            preserve_default=False,
        ),
    ]
