# Generated by Django 5.0.6 on 2024-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.IntegerField(choices=[(2, 'Author'), (3, 'Primary Recipient'), (4, 'Carbon Copy Recipient'), (5, 'Blind Carbon Copy Recipient'), (6, 'Collaborator'), (7, 'Administrator')], help_text='Select the role of this participant.', verbose_name='Roles'),
        ),
    ]
