# Generated by Django 5.0.6 on 2024-07-18 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
