# Generated by Django 5.0.6 on 2024-08-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_tag'),
        ('notifications', '0003_tag_inapp_delete_inappnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='action',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='ready', max_length=50),
        ),
        migrations.RemoveField(
            model_name='email',
            name='tag',
        ),
        migrations.AddField(
            model_name='email',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_tagged_notifications', to='notifications.tag'),
        ),
    ]
