# Generated by Django 5.0.6 on 2024-08-15 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_email_action_alter_email_status_remove_email_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='to',
        ),
        migrations.AddField(
            model_name='email',
            name='to',
            field=models.ManyToManyField(related_name='%(class)s_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
