# Generated by Django 5.0.6 on 2024-10-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationprofile',
            old_name='description',
            new_name='bio',
        ),
    ]
