# Generated by Django 5.0.6 on 2024-10-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organizationprofile_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='auto_date_letters',
            field=models.BooleanField(default=True, help_text='Enable to automatically generate reference numbers for letters. Disable for manual input.', verbose_name='Auto-generate Reference Numbers for Letters'),
        ),
    ]
