# Generated by Django 5.0.6 on 2024-10-07 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=255, verbose_name='Job Title (English)')),
                ('title_am', models.CharField(max_length=255, verbose_name='Job Title (Amharic)')),
            ],
            options={
                'unique_together': {('title_en', 'title_am')},
            },
        ),
    ]
