# Generated by Django 5.0.6 on 2024-05-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.CharField(blank=True, default='Addis Ababa, Ethiopia', help_text='Enter the address of the guest.', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter the email address of the guest.', max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter the phone number of the guest.', max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the postal code of the guest.', null=True, unique=True, verbose_name='Postal Code'),
        ),
    ]
