# Generated by Django 5.0.6 on 2024-10-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_created',
        ),
    ]
