# Generated by Django 5.0.6 on 2024-06-15 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.ForeignKey(help_text='Enter the department of the employee.', on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
    ]
