# Generated by Django 5.0.6 on 2024-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='otp_secret',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
