# Generated by Django 5.0.6 on 2024-07-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='otp_secret',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='OTP Secret'),
        ),
    ]
