# Generated by Django 5.0.6 on 2024-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_member_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
