# Generated by Django 5.0.6 on 2024-07-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_member_is_two_factor_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_two_factor_enabled',
            new_name='is_2fa_enabled',
        ),
    ]
