# Generated by Django 5.0.6 on 2024-08-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        ('participants', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicEnterprise',
            new_name='Enterprise',
        ),
    ]
