# Generated by Django 5.0.6 on 2024-08-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_alter_publicenterprise_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicenterprise',
            name='name_am',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name in Amharic'),
        ),
        migrations.AlterField(
            model_name='publicenterprise',
            name='name_en',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name in English'),
        ),
    ]
