# Generated by Django 5.0.6 on 2024-08-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_alter_publicenterprise_name_am_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
