# Generated by Django 5.0.6 on 2024-08-11 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user'], name='contacts_co_user_id_a88208_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('full_name_en', 'full_name_am', 'address')},
        ),
    ]
