# Generated by Django 5.0.6 on 2024-06-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_alter_letter_current_state_alter_letter_options_and_more'),
        ('permissions', '0001_initial'),
        ('workflows', '0004_alter_workflowlog_action_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
