# Generated by Django 5.0.6 on 2024-07-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letters', '0001_initial'),
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='e_signature',
            field=models.ManyToManyField(blank=True, help_text='Select the senders signature file.', to='signatures.signature'),
        ),
    ]
