# Generated by Django 5.0.6 on 2024-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='reference_number',
            field=models.SlugField(default=1, unique=True, verbose_name='Reference Number'),
            preserve_default=False,
        ),
    ]
