# Generated by Django 5.0.6 on 2024-06-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='owner',
            field=models.ForeignKey(default='fc648bd1-62bb-4f25-9b8e-df5b124b67d0', on_delete=django.db.models.deletion.CASCADE, related_name='owned_letters', to='users.baseuser'),
            preserve_default=False,
        ),
    ]
