# Generated by Django 5.0.6 on 2024-06-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_alter_state_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='permissions',
            new_name='actions',
        ),
    ]
