# Generated by Django 5.0.6 on 2024-06-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'permissions': (('can_view_letter', 'Can view letter'), ('can_update_letter', 'Can update letter'), ('can_delete_letter', 'Can delete letter'), ('can_archive_letter', 'Can archive letter'), ('can_share_letter', 'Can share letter'), ('can_submit_letter', 'Can submit letter'), ('can_retract_letter', 'Can retract letter'), ('can_close_letter', 'Can close letter'), ('can_reopen_letter', 'Can reopen letter'), ('can_comment_letter', 'Can comment letter')), 'verbose_name': 'Letter', 'verbose_name_plural': 'Letters'},
        ),
    ]
