# Generated by Django 5.0.6 on 2024-06-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='owner',
        ),
    ]
