# Generated by Django 5.0.6 on 2024-08-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='pdf_version',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='PDF Version'),
        ),
    ]
