# Generated by Django 5.0.6 on 2024-10-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='reference_number',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='reference_number_am',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
