# Generated by Django 5.0.6 on 2024-10-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_alter_letter_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='published_at',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
    ]
