# Generated by Django 5.0.6 on 2024-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_letter_pdf_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='trashed',
        ),
        migrations.AddField(
            model_name='letter',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('AM', 'Amharic')], default='AM', max_length=2),
        ),
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='current_state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Rejected'), (5, 'Closed'), (6, 'Trashed')]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letter',
            name='pdf_version',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='reference_number',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='delivery_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='delivery_person_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
