# Generated by Django 5.0.6 on 2024-06-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_alter_letter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='submitted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
