# Generated by Django 5.0.6 on 2024-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_remove_letter_trashed_letter_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='reference_number_am',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
