# Generated by Django 5.0.6 on 2024-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_letter_owner'),
        ('workflows', '0004_alter_workflowlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='current_state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Closed')], help_text='Select the current state of the letter.', verbose_name='States'),
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'permissions': (('can_view_letter', 'Can view letter'), ('can_update_letter', 'Can update letter'), ('can_delete_letter', 'Can delete letter'), ('can_archive_letter', 'Can archive letter'), ('can_share_letter', 'Can share letter'), ('can_submit_letter', 'Can submit letter'), ('can_publish_letter', 'Can publish letter'), ('can_retract_letter', 'Can retract letter'), ('can_close_letter', 'Can close letter'), ('can_reopen_letter', 'Can reopen letter'), ('can_comment_letter', 'Can comment letter')), 'verbose_name': 'Letter', 'verbose_name_plural': 'Letters'},
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
