# Generated by Django 5.0.6 on 2024-08-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_letter_reference_number_am'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='content',
            new_name='body',
        ),
    ]
