# Generated by Django 5.0.6 on 2024-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_letter_published_at_letter_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload the signature image for the letter.', null=True, upload_to='letters/signatures/', verbose_name='Signature'),
        ),
    ]
