# Generated by Django 5.0.6 on 2024-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_remove_letter_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='signature',
            field=models.FileField(default=1, help_text='Upload the author signature file.', upload_to='letters/signatures/', verbose_name='Signature'),
            preserve_default=False,
        ),
    ]
