# Generated by Django 5.0.6 on 2024-07-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_letter_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'permissions': (('can_view_letter', 'Can view letter'), ('can_update_letter', 'Can update letter'), ('can_archive_letter', 'Can archive letter'), ('can_share_letter', 'Can share letter'), ('can_submit_letter', 'Can submit letter'), ('can_publish_letter', 'Can publish letter'), ('can_reject_letter', 'Can reopen letter'), ('can_retract_letter', 'Can retract letter'), ('can_close_letter', 'Can close letter'), ('can_reopen_letter', 'Can reopen letter'), ('can_comment_letter', 'Can comment letter'), ('can_trash_letter', 'Can trash letter'), ('can_restore_letter', 'Can restore letter'), ('can_remove_from_trash_letter', 'Can remove from trash letter')), 'verbose_name': 'Letter', 'verbose_name_plural': 'Letters'},
        ),
        migrations.RemoveField(
            model_name='letter',
            name='owner',
        ),
        migrations.AddField(
            model_name='letter',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
        migrations.AddField(
            model_name='letter',
            name='trashed',
            field=models.BooleanField(default=False, verbose_name='Trashed'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='current_state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Closed'), (5, 'Deleted')], help_text='Select the current state of the letter.', verbose_name='States'),
        ),
    ]
