# Generated by Django 5.0.6 on 2024-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_alter_letter_options_remove_letter_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='current_state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Closed'), (5, 'Trashed')], help_text='Select the current state of the letter.', verbose_name='States'),
        ),
    ]
