# Generated by Django 5.0.6 on 2024-07-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0010_alter_letter_current_state'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_letters', to='users.baseuser'),
            preserve_default=False,
        ),
    ]
