# Generated by Django 5.0.6 on 2024-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0015_remove_letter_signature_alter_letter_owner'),
        ('signatures', '0003_alter_signature_e_signature_alter_signature_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='e_signature',
            field=models.ManyToManyField(blank=True, help_text='Select the senders signature file.', to='signatures.signature'),
        ),
    ]
