# Generated by Django 5.0.6 on 2024-10-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='database_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Database Name'),
        ),
    ]
