# Generated by Django 5.0.6 on 2024-10-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_database_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together=set(),
        ),
    ]
