# Generated by Django 5.0.6 on 2024-10-10 08:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenant_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('name_en', 'owner')},
        ),
    ]
