# Generated by Django 5.0.6 on 2024-10-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together=set(),
        ),
    ]
