# Generated by Django 5.0.6 on 2024-10-11 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_tenantprofile_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('name_en', 'name_am', 'owner')},
        ),
    ]
