# Generated by Django 5.0.6 on 2024-08-03 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_am', models.CharField(max_length=255)),
                ('abbreviation_en', models.CharField(max_length=3)),
                ('abbreviation_am', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_phone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'unique_together': {('name_en', 'name_am', 'abbreviation_en', 'abbreviation_am')},
            },
        ),
    ]
