# Generated by Django 5.0.6 on 2024-10-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('user_management', '0002_alter_userprofile_job_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTitle',
        ),
    ]
