# Generated by Django 5.0.6 on 2024-10-11 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('job_titles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(unique=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'unique_together': {('user_id',)},
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_permissions', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Permission',
                'verbose_name_plural': 'Member Permissions',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_preference', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Preference',
                'verbose_name_plural': 'Member Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name_en', models.CharField(blank=True, max_length=35, verbose_name='First Name (English)')),
                ('middle_name_en', models.CharField(blank=True, max_length=35, verbose_name='Middle Name (English)')),
                ('last_name_en', models.CharField(blank=True, max_length=35, verbose_name='Last Name (English)')),
                ('first_name_am', models.CharField(blank=True, max_length=35, verbose_name='First Name (Amharic)')),
                ('middle_name_am', models.CharField(blank=True, max_length=35, verbose_name='Middle Name (Amharic)')),
                ('last_name_am', models.CharField(blank=True, max_length=35, verbose_name='Last Name (Amharic)')),
                ('phone_number', models.PositiveBigIntegerField(unique=True, verbose_name='phone number')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_titles.jobtitle')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_settings', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Setting',
                'verbose_name_plural': 'Member Settings',
            },
        ),
    ]
