# Generated by Django 5.0.6 on 2024-10-10 05:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('member',)},
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('member',)},
        ),
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together={('member',)},
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_permissions', to='user_management.member')),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'unique_together': {('member',)},
            },
        ),
    ]
