# Generated by Django 5.0.6 on 2024-10-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_userpreference_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
