# Generated by Django 5.0.6 on 2024-10-11 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('job_titles', '0001_initial'),
        ('members', '0002_alter_memberprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_titles.jobtitle'),
        ),
    ]
