# Generated by Django 5.0.6 on 2024-10-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_rename_is_first_time_usersetting_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_preference', to='user_management.member'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to='user_management.member'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_settings', to='user_management.member'),
        ),
    ]
