# Generated by Django 5.0.6 on 2024-10-10 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_userpreference_member_alter_userprofile_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_permissions', to='user_management.member'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user_id',)},
        ),
    ]
