# Generated by Django 5.0.6 on 2024-08-15 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_tag_inapp_delete_inappnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inapp',
            name='to',
        ),
        migrations.AddField(
            model_name='inapp',
            name='to',
            field=models.ManyToManyField(related_name='%(class)s_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
