# Generated by Django 5.0.6 on 2024-08-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_inapp_to_inapp_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InApp',
        ),
    ]
