# Generated by Django 5.0.6 on 2024-06-21 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='The action that was performed.', max_length=50, verbose_name='Action')),
                ('role', models.CharField(help_text='The role of the user at the time of the action.', max_length=50, verbose_name='Role')),
                ('initial_state', models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Closed')], help_text='The state of the resource before the action was performed.', verbose_name='Initial State')),
                ('final_state', models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Closed')], help_text='The state of the resource after the action was performed.', verbose_name='Final State')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the action was performed.', verbose_name='Timestamp')),
                ('success', models.BooleanField(help_text='Indicates whether the action was successful.', verbose_name='Success')),
                ('actor', models.ForeignKey(help_text='The user who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('resource', models.ForeignKey(help_text='The resource that was accessed or modified.', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='letters.letter', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'Workflow Log',
                'verbose_name_plural': 'Workflow Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
