# Generated by Django 5.0.6 on 2024-06-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Workflow Log', 'verbose_name_plural': 'Workflow Logs'},
        ),
        migrations.RenameField(
            model_name='workflowlog',
            old_name='user',
            new_name='actor',
        ),
    ]
