# Generated by Django 5.0.6 on 2024-06-19 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflowlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlog',
            name='actor',
            field=models.ForeignKey(help_text='The user who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
