# Generated by Django 5.0.6 on 2024-07-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflowlog_final_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlog',
            name='final_state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Rejected'), (5, 'Closed'), (6, 'Trashed')], help_text='The state of the resource after the action was performed.', verbose_name='Final State'),
        ),
        migrations.AlterField(
            model_name='workflowlog',
            name='initial_state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Rejected'), (5, 'Closed'), (6, 'Trashed')], help_text='The state of the resource before the action was performed.', verbose_name='Initial State'),
        ),
    ]
