# Generated by Django 5.0.6 on 2024-10-04 09:06

import core.signatures.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_image', models.ImageField(upload_to=core.signatures.models.signature_directory_path, verbose_name='Signature Image')),
                ('signature_method', models.IntegerField(choices=[(1, 'Default'), (2, 'Canvas')], verbose_name='Signature Method')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_signatures', to='letters.letter', verbose_name='Letter')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Signer')),
            ],
            options={
                'verbose_name': 'Letter Signature',
                'verbose_name_plural': 'Letter Signatures',
                'db_table': 'letter_signature',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDefaultSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_image', models.ImageField(upload_to=core.signatures.models.signature_directory_path, verbose_name='Signature Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_signature', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
