# Generated by Django 5.0.6 on 2024-07-25 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this signature.', on_delete=django.db.models.deletion.CASCADE, related_name='e_signature', to=settings.AUTH_USER_MODEL),
        ),
    ]
