# Generated by Django 5.0.6 on 2024-07-18 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_alter_signature_e_signature_alter_signature_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='e_signature',
            field=models.ImageField(help_text='Upload your signature image file.', unique=True, upload_to='letters/signatures/', verbose_name='E Signature'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this signature.', on_delete=django.db.models.deletion.CASCADE, related_name='e_signature', to=settings.AUTH_USER_MODEL),
        ),
    ]
